### PR TITLE
fix(factory): trigger animation on entering

### LINKED ISSUE #17: entering styles don't get applied until entered state
I think there's something wrong with [this block](https://github.com/Setsun/react-transition-factory/blob/master/src/factory/index.js#L104-L120) but i havent really figured it out yet.

When a component mounts, it is in the "exited" state, but the `startStyle` is applied since `exited` = `entering`. This means when exited->entering->entered, the styles are actually startStyle->startStyle->endStyle, which means the transition only starts to take effect when we are in the entered state.

I've temporarily fixed this in my component by manually applying the exited styles on the child component (to force a transition basically), but I think we need to fix which style is applied when

### PR DESCRIPTION
**Pull request by Joelkang**
fixes https://github.com/Setsun/react-transition-factory/issues/17

### CODE REVIEW

File: src/factory/index.js [hunk 1]
```diff
@@ -101,10 +101,15 @@ const transitionFactory = (...args: Array<any>) => {
           const endVal = getPrimitiveValue(end, index);
           const transitionName = camelCase(transition.transition);
 
+          styles.exited[transitionName] = getStyleString(
+            transitionName,
+            styles.exited[transitionName],
+            transition.getStartStyle(startVal)
+          );
```
Comment (setsun) [inline src/factory/index.js:108]: noice, only thing I'll say is a preference to put this after `styles.exiting` to have these in chronological order

**Review by setsun — APPROVED** [review]

File: src/factory/index.js (hunk 1 above)
Comment (Joelkang) [reply src/factory/index.js:108]: technically every component starts from the exited state

sidenote: what is this currentStyle thing for `transforms`?
